// The Hollywood & Highland roster — 12 hand-authored souls built on the locked
// archetype list. Structured for the engine to tick; a procedural generator can
// replace this file wholesale in Phase 5 without touching anything else.

import {
  type Soul,
  type Traits,
  type ChakraName,
  CHAKRA_ORDER,
} from "./types.ts";

function traits(p: Partial<Traits>): Traits {
  return {
    negativeAffectivity: 30,
    detachment: 30,
    antagonism: 25,
    disinhibition: 30,
    psychoticism: 20,
    ...p,
  };
}

function chakras(vals: [number, number, number, number, number, number, number]) {
  const out = {} as Record<ChakraName, number>;
  CHAKRA_ORDER.forEach((name, i) => {
    out[name] = vals[i];
  });
  return out;
}

type Seed = Omit<Soul, "emotion" | "activity"> & Partial<Pick<Soul, "emotion" | "activity">>;

function soul(seed: Seed): Soul {
  return {
    emotion: { primary: "neutral", intensity: 30 },
    activity: "wander",
    ...seed,
  };
}

export const ROSTER: Soul[] = [
  soul({
    id: "danny",
    name: "Danny Rios",
    occupation: 'Costumed Character Performer ("Robo-Hero")',
    archetype: "Costumed Street Performer",
    age: 34,
    narrative:
      "Three failed auditions this year. The suit pays the rent the way the craft never did. He tells himself it's temporary — the way he has for six years.",
    needs: { survival: 26, safety: 34, belonging: 40, esteem: 30, actualization: 44 },
    traits: traits({ negativeAffectivity: 58, detachment: 20, disinhibition: 35 }),
    aceScore: 3,
    resilience: 48,
    kohlberg: 3,
    soulAge: "Mature",
    initiationLevel: 1,
    chakras: chakras([28, 40, 32, 46, 24, 40, 12]),
    consciousAspiration: "Finally get cast — become a real actor",
    soulPurpose: "Bring a moment of delight to strangers who need it",
    affinities: { perform: 1.6, work: 1.2, rest: 1.1 },
    row: "north",
    xMin: 100,
    xMax: 320,
    baseSpeed: 26,
  }),
  soul({
    id: "trish",
    name: "Trish Anderson",
    occupation: "Tourist, Dayton, Ohio",
    archetype: "Tourist",
    age: 29,
    narrative:
      "She has wanted to stand on this sidewalk since she was eleven. For a few seconds outside the Chinese Theatre, her whole chest went quiet.",
    needs: { survival: 72, safety: 68, belonging: 42, esteem: 55, actualization: 64 },
    traits: traits({ negativeAffectivity: 35, detachment: 22 }),
    aceScore: 1,
    resilience: 70,
    kohlberg: 4,
    soulAge: "Mature",
    initiationLevel: 2,
    chakras: chakras([70, 66, 54, 62, 48, 52, 34]),
    consciousAspiration: "Capture the trip of a lifetime",
    soulPurpose: "Rediscover the wonder she buried under adult routine",
    affinities: { gaze: 1.7, socialize: 1.2 },
    row: "north",
    xMin: 640,
    xMax: 1050,
    baseSpeed: 18,
  }),
  soul({
    id: "frank",
    name: "Frank Castellano",
    occupation: "Freelance Photographer",
    archetype: "Paparazzi",
    age: 47,
    narrative:
      "He hasn't sold a real cover shot in eight months. He's stopped calling it stalking, even in his own head.",
    needs: { survival: 48, safety: 44, belonging: 30, esteem: 34, actualization: 30 },
    traits: traits({ antagonism: 68, detachment: 55, disinhibition: 50, negativeAffectivity: 52 }),
    aceScore: 4,
    resilience: 40,
    kohlberg: 2,
    soulAge: "Mature",
    initiationLevel: 1,
    chakras: chakras([46, 30, 40, 22, 42, 50, 14]),
    consciousAspiration: "Land the one shot that fixes everything",
    soulPurpose: "Bear honest witness instead of feeding the machine",
    affinities: { hustle: 1.7, work: 1.1 },
    row: "south",
    xMin: 250,
    xMax: 560,
    baseSpeed: 22,
  }),
  soul({
    id: "vivian",
    name: "Vivian Laurent",
    occupation: "Former Screen Actress (credits: 1990s)",
    archetype: "Faded Star",
    age: 61,
    narrative:
      "People still recognize her — less every year. She still walks this block every afternoon, in case someone does.",
    needs: { survival: 60, safety: 38, belonging: 30, esteem: 44, actualization: 40 },
    traits: traits({ negativeAffectivity: 55, detachment: 40 }),
    aceScore: 2,
    resilience: 52,
    kohlberg: 4,
    soulAge: "Old",
    initiationLevel: 3,
    chakras: chakras([58, 48, 46, 30, 48, 54, 30]),
    consciousAspiration: "Be remembered — matter again",
    soulPurpose: "Pass her hard-won craft to someone just starting out",
    affinities: { reminisce: 1.6, socialize: 1.3, gaze: 1.1 },
    row: "north",
    xMin: 1080,
    xMax: 1500,
    baseSpeed: 14,
  }),
  soul({
    id: "bailey",
    name: "Bailey Okafor",
    occupation: "Server, Auditioning Nights",
    archetype: "Industry Aspirant",
    age: 24,
    narrative:
      "Her agent hasn't called back in nine days. She rehearses the callback she hasn't gotten yet, out loud, on her walk to work.",
    needs: { survival: 52, safety: 50, belonging: 58, esteem: 30, actualization: 56 },
    traits: traits({ negativeAffectivity: 48, detachment: 18 }),
    aceScore: 2,
    resilience: 62,
    kohlberg: 4,
    soulAge: "Young",
    initiationLevel: 2,
    chakras: chakras([56, 60, 44, 62, 30, 48, 28]),
    consciousAspiration: "Book the role that changes everything",
    soulPurpose: "Become a source of steadiness for the people she came from",
    affinities: { work: 1.4, perform: 1.3, socialize: 1.2 },
    row: "south",
    xMin: 650,
    xMax: 980,
    baseSpeed: 24,
  }),
  soul({
    id: "marcus",
    name: "Marcus Webb",
    occupation: "Rideshare Driver",
    archetype: "Local Commuter",
    age: 39,
    narrative:
      "Just passing through this block on the way to the next fare. Two kids at home; the math never quite works.",
    needs: { survival: 55, safety: 46, belonging: 58, esteem: 52, actualization: 50 },
    traits: traits({ negativeAffectivity: 38 }),
    aceScore: 1,
    resilience: 66,
    kohlberg: 4,
    soulAge: "Mature",
    initiationLevel: 2,
    chakras: chakras([60, 62, 60, 58, 62, 56, 34]),
    consciousAspiration: "Get out from under the debt",
    soulPurpose: "Be the steady presence his kids can count on",
    affinities: { work: 1.5, wander: 1.2 },
    row: "south",
    xMin: 60,
    xMax: 240,
    baseSpeed: 30,
  }),
  soul({
    id: "priya",
    name: "Priya Chandra",
    occupation: "Souvenir Shop Clerk",
    archetype: "Local Worker",
    age: 21,
    narrative:
      "Another shift, another thousand tourists asking where the stars are. She still likes the job, mostly.",
    needs: { survival: 58, safety: 60, belonging: 62, esteem: 50, actualization: 54 },
    traits: traits({ detachment: 18 }),
    aceScore: 0,
    resilience: 72,
    kohlberg: 4,
    soulAge: "Young",
    initiationLevel: 2,
    chakras: chakras([64, 66, 62, 66, 50, 58, 34]),
    consciousAspiration: "Save enough for community college",
    soulPurpose: "Offer warmth to strangers far from home",
    affinities: { socialize: 1.4, work: 1.2 },
    row: "north",
    xMin: 360,
    xMax: 560,
    baseSpeed: 16,
  }),
  soul({
    id: "hank",
    name: "Hank Torres",
    occupation: "Walking Tour Guide",
    archetype: "Local Worker",
    age: 52,
    narrative:
      "Twelve tours a week, same jokes, same facts. He still means it when he points out the stars — mostly.",
    needs: { survival: 56, safety: 58, belonging: 54, esteem: 44, actualization: 52 },
    traits: traits({ negativeAffectivity: 40 }),
    aceScore: 1,
    resilience: 60,
    kohlberg: 4,
    soulAge: "Mature",
    initiationLevel: 2,
    chakras: chakras([60, 58, 52, 60, 62, 50, 32]),
    consciousAspiration: "Be respected as the guy who knows this city",
    soulPurpose: "Keep the boulevard's real stories alive",
    affinities: { perform: 1.3, work: 1.4, socialize: 1.1 },
    row: "north",
    xMin: 1120,
    xMax: 1480,
    baseSpeed: 20,
  }),
  soul({
    id: "sasha",
    name: "Sasha Kane",
    occupation: "Lifestyle Content Creator",
    archetype: "Reality-TV Influencer",
    age: 27,
    narrative:
      "Four hundred thousand followers and she still refreshes the numbers at red lights. The camera is the only place she feels real.",
    needs: { survival: 66, safety: 60, belonging: 34, esteem: 28, actualization: 46 },
    traits: traits({ antagonism: 58, disinhibition: 60, negativeAffectivity: 50, detachment: 30 }),
    aceScore: 3,
    resilience: 44,
    kohlberg: 3,
    soulAge: "Young",
    initiationLevel: 1,
    chakras: chakras([62, 50, 44, 28, 40, 44, 16]),
    consciousAspiration: "Go viral — become undeniable",
    soulPurpose: "Risk one honest, unfiltered connection",
    affinities: { hustle: 1.5, perform: 1.5 },
    row: "south",
    xMin: 1000,
    xMax: 1200,
    baseSpeed: 23,
  }),
  soul({
    id: "gerald",
    name: "Gerald Ostrow",
    occupation: "Studio Executive",
    archetype: "Mogul / Producer",
    age: 58,
    narrative:
      "He can greenlight a hundred million dollars before lunch. He can't remember the last conversation that wasn't a negotiation.",
    needs: { survival: 88, safety: 82, belonging: 26, esteem: 70, actualization: 40 },
    traits: traits({ antagonism: 60, detachment: 62, negativeAffectivity: 30 }),
    aceScore: 4,
    resilience: 58,
    kohlberg: 2,
    soulAge: "Mature",
    initiationLevel: 1,
    chakras: chakras([80, 44, 66, 24, 50, 46, 14]),
    consciousAspiration: "Land the franchise that cements his legacy",
    soulPurpose: "Use his power to shelter the people the machine chews up",
    affinities: { work: 1.6, hustle: 1.3 },
    row: "north",
    xMin: 600,
    xMax: 900,
    baseSpeed: 21,
  }),
  soul({
    id: "cody",
    name: "Cody Vance",
    occupation: "Busker (former child actor)",
    archetype: "Former Child Star / Busker",
    age: 31,
    narrative:
      "America watched him grow up on a sitcom. The residuals ran out a decade ago. He plays the theme song for tips and hates that it still works.",
    needs: { survival: 30, safety: 32, belonging: 34, esteem: 38, actualization: 42 },
    traits: traits({ negativeAffectivity: 66, disinhibition: 58, detachment: 40 }),
    aceScore: 6,
    resilience: 34,
    kohlberg: 3,
    soulAge: "Mature",
    initiationLevel: 2,
    chakras: chakras([30, 34, 34, 38, 40, 46, 18]),
    consciousAspiration: "Engineer the comeback everyone owes him",
    soulPurpose: "Protect the next generation of kids from what happened to him",
    affinities: { perform: 1.5, reminisce: 1.4, rest: 1.1 },
    row: "south",
    xMin: 300,
    xMax: 520,
    baseSpeed: 17,
  }),
  soul({
    id: "mateo",
    name: "Mateo Ruiz",
    occupation: "Street Musician",
    archetype: "Old Soul / Street Musician",
    age: 44,
    narrative:
      "He plays where the acoustics are best, gives half his tips away, and somehow people stand a little straighter after they pass him. He'd tell you it's just the guitar.",
    needs: { survival: 58, safety: 62, belonging: 74, esteem: 66, actualization: 82 },
    traits: traits({ negativeAffectivity: 18, detachment: 15, antagonism: 12 }),
    aceScore: 5,
    resilience: 90,
    kohlberg: 6,
    soulAge: "Old",
    initiationLevel: 5,
    chakras: chakras([78, 76, 74, 78, 76, 72, 66]),
    consciousAspiration: "Just play, and pay rent",
    soulPurpose: "Be a tuning fork the whole block quietly aligns to",
    affinities: { perform: 1.3, socialize: 1.4, gaze: 1.2 },
    row: "north",
    xMin: 360,
    xMax: 620,
    baseSpeed: 15,
  }),
];
