// The Hollywood & Highland roster — 12 hand-authored souls built on the locked
// archetype list. Structured for the engine to tick; a procedural generator can
// replace this file wholesale in Phase 5 without touching anything else.

import {
  type Soul,
  type Traits,
  type ChakraName,
  CHAKRA_ORDER,
} from "./types.ts";

function traits(p: Partial<Traits>): Traits {
  return {
    negativeAffectivity: 30,
    detachment: 30,
    antagonism: 25,
    disinhibition: 30,
    psychoticism: 20,
    ...p,
  };
}

function chakras(vals: [number, number, number, number, number, number, number]) {
  const out = {} as Record<ChakraName, number>;
  CHAKRA_ORDER.forEach((name, i) => {
    out[name] = vals[i];
  });
  return out;
}

type Seed = Omit<Soul, "emotion" | "activity"> & Partial<Pick<Soul, "emotion" | "activity">>;

function soul(seed: Seed): Soul {
  return {
    emotion: { primary: "neutral", intensity: 30 },
    activity: "wander",
    ...seed,
  };
}

export const ROSTER: Soul[] = [
  soul({
    id: "danny",
    name: "Danny Rios",
    occupation: 'Costumed Character Performer ("Robo-Hero")',
    archetype: "Costumed Street Performer",
    age: 34,
    narrative:
      "Three failed auditions this year. The suit pays the rent the way the craft never did. He tells himself it's temporary — the way he has for six years.",
    needs: { survival: 26, safety: 34, belonging: 40, esteem: 30, actualization: 44 },
    traits: traits({ negativeAffectivity: 58, detachment: 20, disinhibition: 35 }),
    aceScore: 3,
    resilience: 48,
    kohlberg: 3,
    soulAge: "Mature",
    initiationLevel: 1,
    chakras: chakras([28, 40, 32, 46, 24, 40, 12]),
    consciousAspiration: "Finally get cast — become a real actor",
    soulPurpose: "Bring a moment of delight to strangers who need it",
    affinities: { perform: 1.6, work: 1.2, rest: 1.1 },
    row: "north",
    xMin: 100,
    xMax: 320,
    baseSpeed: 26,
  }),
  soul({
    id: "trish",
    name: "Trish Anderson",
    occupation: "Tourist, Dayton, Ohio",
    archetype: "Tourist",
    age: 29,
    narrative:
      "She has wanted to stand on this sidewalk since she was eleven. For a few seconds outside the Chinese Theatre, her whole chest went quiet.",
    needs: { survival: 72, safety: 68, belonging: 42, esteem: 55, actualization: 64 },
    traits: traits({ negativeAffectivity: 35, detachment: 22 }),
    aceScore: 1,
    resilience: 70,
    kohlberg: 4,
    soulAge: "Mature",
    initiationLevel: 2,
    chakras: chakras([70, 66, 54, 62, 48, 52, 34]),
    consciousAspiration: "Capture the trip of a lifetime",
    soulPurpose: "Rediscover the wonder she buried under adult routine",
    affinities: { gaze: 1.7, socialize: 1.2 },
    row: "north",
    xMin: 640,
    xMax: 1050,
    baseSpeed: 18,
  }),
  soul({
    id: "frank",
    name: "Frank Castellano",
    occupation: "Freelance Photographer",
    archetype: "Paparazzi",
    age: 47,
    narrative:
      "He hasn't sold a real cover shot in eight months. He's stopped calling it stalking, even in his own head.",
    needs: { survival: 48, safety: 44, belonging: 30, esteem: 34, actualization: 30 },
    traits: traits({ antagonism: 68, detachment: 55, disinhibition: 50, negativeAffectivity: 52 }),
    aceScore: 4,
    resilience: 40,
    kohlberg: 2,
    soulAge: "Mature",
    initiationLevel: 1,
    chakras: chakras([46, 30, 40, 22, 42, 50, 14]),
    consciousAspiration: "Land the one shot that fixes everything",
    soulPurpose: "Bear honest witness instead of feeding the machine",
    affinities: { hustle: 1.7, work: 1.1 },
    row: "south",
    xMin: 250,
    xMax: 560,
    baseSpeed: 22,
  }),
  soul({
    id: "vivian",
    name: "Vivian Laurent",
    occupation: "Former Screen Actress (credits: 1990s)",
    archetype: "Faded Star",
    age: 61,
    narrative:
      "People still recognize her — less every year. She still walks this block every afternoon, in case someone does.",
    needs: { survival: 60, safety: 38, belonging: 30, esteem: 44, actualization: 40 },
    traits: traits({ negativeAffectivity: 55, detachment: 40 }),
    aceScore: 2,
    resilience: 52,
    kohlberg: 4,
    soulAge: "Old",
    initiationLevel: 3,
    chakras: chakras([58, 48, 46, 30, 48, 54, 30]),
    consciousAspiration: "Be remembered — matter again",
    soulPurpose: "Pass her hard-won craft to someone just starting out",
    affinities: { reminisce: 1.6, socialize: 1.3, gaze: 1.1 },
    row: "north",
    xMin: 1080,
    xMax: 1500,
    baseSpeed: 14,
  }),
  soul({
    id: "bailey",
    name: "Bailey Okafor",
    occupation: "Server, Auditioning Nights",
    archetype: "Industry Aspirant",
    age: 24,
    narrative:
      "Her agent hasn't called back in nine days. She rehearses the callback she hasn't gotten yet, out loud, on her walk to work.",
    needs: { survival: 52, safety: 50, belonging: 58, esteem: 30, actualization: 56 },
    traits: traits({ negativeAffectivity: 48, detachment: 18 }),
    aceScore: 2,
    resilience: 62,
    kohlberg: 4,
    soulAge: "Young",
    initiationLevel: 2,
    chakras: chakras([56, 60, 44, 62, 30, 48, 28]),
    consciousAspiration: "Book the role that changes everything",
    soulPurpose: "Become a source of steadiness for the people she came from",
    affinities: { work: 1.4, perform: 1.3, socialize: 1.2 },
    row: "south",
    xMin: 650,
    xMax: 980,
    baseSpeed: 24,
  }),
  soul({
    id: "marcus",
    name: "Marcus Webb",
    occupation: "Rideshare Driver",
    archetype: "Local Commuter",
    age: 39,
    narrative:
      "Just passing through this block on the way to the next fare. Two kids at home; the math never quite works.",
    needs: { survival: 55, safety: 46, belonging: 58, esteem: 52, actualization: 50 },
    traits: traits({ negativeAffectivity: 38 }),
    aceScore: 1,
    resilience: 66,
    kohlberg: 4,
    soulAge: "Mature",
    initiationLevel: 2,
    chakras: chakras([60, 62, 60, 58, 62, 56, 34]),
    consciousAspiration: "Get out from under the debt",
    soulPurpose: "Be the steady presence his kids can count on",
    affinities: { work: 1.5, wander: 1.2 },
    row: "south",
    xMin: 60,
    xMax: 240,
    baseSpeed: 30,
  }),
  soul({
    id: "priya",
    name: "Priya Chandra",
    occupation: "Souvenir Shop Clerk",
    archetype: "Local Worker",
    age: 21,
    narrative:
      "Another shift, another thousand tourists asking where the stars are. She still likes the job, mostly.",
    needs: { survival: 58, safety: 60, belonging: 62, esteem: 50, actualization: 54 },
    traits: traits({ detachment: 18 }),
    aceScore: 0,
    resilience: 72,
    kohlberg: 4,
    soulAge: "Young",
    initiationLevel: 2,
    chakras: chakras([64, 66, 62, 66, 50, 58, 34]),
    consciousAspiration: "Save enough for community college",
    soulPurpose: "Offer warmth to strangers far from home",
    affinities: { socialize: 1.4, work: 1.2 },
    row: "north",
    xMin: 360,
    xMax: 560,
    baseSpeed: 16,
  }),
  soul({
    id: "hank",
    name: "Hank Torres",
    occupation: "Walking Tour Guide",
    archetype: "Local Worker",
    age: 52,
    narrative:
      "Twelve tours a week, same jokes, same facts. He still means it when he points out the stars — mostly.",
    needs: { survival: 56, safety: 58, belonging: 54, esteem: 44, actualization: 52 },
    traits: traits({ negativeAffectivity: 40 }),
    aceScore: 1,
    resilience: 60,
    kohlberg: 4,
    soulAge: "Mature",
    initiationLevel: 2,
    chakras: chakras([60, 58, 52, 60, 62, 50, 32]),
    consciousAspiration: "Be respected as the guy who knows this city",
    soulPurpose: "Keep the boulevard's real stories alive",
    affinities: { perform: 1.3, work: 1.4, socialize: 1.1 },
    row: "north",
    xMin: 1120,
    xMax: 1480,
    baseSpeed: 20,
  }),
  soul({
    id: "sasha",
    name: "Sasha Kane",
    occupation: "Lifestyle Content Creator",
    archetype: "Reality-TV Influencer",
    age: 27,
    narrative:
      "Four hundred thousand followers and she still refreshes the numbers at red lights. The camera is the only place she feels real.",
    needs: { survival: 66, safety: 60, belonging: 34, esteem: 28, actualization: 46 },
    traits: traits({ antagonism: 58, disinhibition: 60, negativeAffectivity: 50, detachment: 30 }),
    aceScore: 3,
    resilience: 44,
    kohlberg: 3,
    soulAge: "Young",
    initiationLevel: 1,
    chakras: chakras([62, 50, 44, 28, 40, 44, 16]),
    consciousAspiration: "Go viral — become undeniable",
    soulPurpose: "Risk one honest, unfiltered connection",
    affinities: { hustle: 1.5, perform: 1.5 },
    row: "south",
    xMin: 1000,
    xMax: 1200,
    baseSpeed: 23,
  }),
  soul({
    id: "gerald",
    name: "Gerald Ostrow",
    occupation: "Studio Executive",
    archetype: "Mogul / Producer",
    age: 58,
    narrative:
      "He can greenlight a hundred million dollars before lunch. He can't remember the last conversation that wasn't a negotiation.",
    needs: { survival: 88, safety: 82, belonging: 26, esteem: 70, actualization: 40 },
    traits: traits({ antagonism: 60, detachment: 62, negativeAffectivity: 30 }),
    aceScore: 4,
    resilience: 58,
    kohlberg: 2,
    soulAge: "Mature",
    initiationLevel: 1,
    chakras: chakras([80, 44, 66, 24, 50, 46, 14]),
    consciousAspiration: "Land the franchise that cements his legacy",
    soulPurpose: "Use his power to shelter the people the machine chews up",
    affinities: { work: 1.6, hustle: 1.3 },
    row: "north",
    xMin: 600,
    xMax: 900,
    baseSpeed: 21,
  }),
  soul({
    id: "cody",
    name: "Cody Vance",
    occupation: "Busker (former child actor)",
    archetype: "Former Child Star / Busker",
    age: 31,
    narrative:
      "America watched him grow up on a sitcom. The residuals ran out a decade ago. He plays the theme song for tips and hates that it still works.",
    needs: { survival: 30, safety: 32, belonging: 34, esteem: 38, actualization: 42 },
    traits: traits({ negativeAffectivity: 66, disinhibition: 58, detachment: 40 }),
    aceScore: 6,
    resilience: 34,
    kohlberg: 3,
    soulAge: "Mature",
    initiationLevel: 2,
    chakras: chakras([30, 34, 34, 38, 40, 46, 18]),
    consciousAspiration: "Engineer the comeback everyone owes him",
    soulPurpose: "Protect the next generation of kids from what happened to him",
    affinities: { perform: 1.5, reminisce: 1.4, rest: 1.1 },
    row: "south",
    xMin: 300,
    xMax: 520,
    baseSpeed: 17,
  }),
  soul({
    id: "mateo",
    name: "Mateo Ruiz",
    occupation: "Street Musician",
    archetype: "Old Soul / Street Musician",
    age: 44,
    narrative:
      "He plays where the acoustics are best, gives half his tips away, and somehow people stand a little straighter after they pass him. He'd tell you it's just the guitar.",
    needs: { survival: 58, safety: 62, belonging: 74, esteem: 66, actualization: 82 },
    traits: traits({ negativeAffectivity: 18, detachment: 15, antagonism: 12 }),
    aceScore: 5,
    resilience: 90,
    kohlberg: 6,
    soulAge: "Old",
    initiationLevel: 5,
    chakras: chakras([78, 76, 74, 78, 76, 72, 66]),
    consciousAspiration: "Just play, and pay rent",
    soulPurpose: "Be a tuning fork the whole block quietly aligns to",
    affinities: { perform: 1.3, socialize: 1.4, gaze: 1.2 },
    row: "north",
    xMin: 360,
    xMax: 620,
    baseSpeed: 15,
  }),

  // --- the Ivar Ave set: three souls in the same colors, three different truths.
  // Their clothing all reads "faction-coded" — the block can't tell them apart on
  // sight. Only the god (reading the panel) sees the shot-caller, the starving kid,
  // and the one already halfway out the door.
  soul({
    id: "hector",
    name: "Hector Reyes",
    occupation: "Corner Veteran",
    archetype: "Gang Shot-Caller",
    faction: "the Ivar Ave set",
    age: 38,
    narrative:
      "He runs this corner the only way he was ever shown — by making sure no one forgets who he is. The respect is real. So is the exhaustion he never lets anyone see.",
    needs: { survival: 58, safety: 50, belonging: 46, esteem: 62, actualization: 26 },
    traits: traits({ antagonism: 72, detachment: 60, disinhibition: 55, negativeAffectivity: 44, psychoticism: 34 }),
    aceScore: 7,
    resilience: 46,
    kohlberg: 2,
    soulAge: "Mature",
    initiationLevel: 1,
    chakras: chakras([50, 34, 52, 22, 30, 34, 12]),
    consciousAspiration: "Keep the block ours — command respect, never look weak",
    soulPurpose: "Protect his people, and find the strength to finally lay the weapon down",
    affinities: { hustle: 1.5, work: 1.1, socialize: 1.1, rest: 1.0 },
    row: "south",
    xMin: 1300,
    xMax: 1520,
    baseSpeed: 10,
  }),
  soul({
    id: "javi",
    name: "Javier Mendez",
    occupation: 'Neighborhood Kid ("Lil J")',
    archetype: "Gang Initiate",
    faction: "the Ivar Ave set",
    age: 17,
    narrative:
      "He'd never say it out loud, but he joined for the thing he never got at home — people who show up. He'd do almost anything to keep them, and the older ones know it.",
    needs: { survival: 44, safety: 32, belonging: 26, esteem: 30, actualization: 40 },
    traits: traits({ negativeAffectivity: 58, detachment: 20, antagonism: 40, disinhibition: 62, psychoticism: 22 }),
    aceScore: 8,
    resilience: 44,
    kohlberg: 3,
    soulAge: "Young",
    initiationLevel: 1,
    chakras: chakras([24, 30, 28, 40, 26, 30, 14]),
    consciousAspiration: "Prove I'm down — earn my place, make them proud",
    soulPurpose: "Find the family and safety he's actually starving for, before the street takes him",
    affinities: { socialize: 1.5, perform: 1.2, hustle: 1.2, rest: 1.0 },
    row: "south",
    xMin: 1260,
    xMax: 1500,
    baseSpeed: 16,
  }),
  soul({
    id: "ruben",
    name: "Ruben Salcedo",
    occupation: "Auto-Shop Apprentice",
    archetype: "Getting Out",
    faction: "the Ivar Ave set",
    age: 26,
    narrative:
      "He grew up in these colors and still wears them — this is his neighborhood, his people. But he clocks in at the shop now, and every day he's quietly building a door his little brother can walk through.",
    needs: { survival: 60, safety: 54, belonging: 66, esteem: 58, actualization: 62 },
    traits: traits({ negativeAffectivity: 34, detachment: 22, antagonism: 28, disinhibition: 30, psychoticism: 18 }),
    aceScore: 6,
    resilience: 74,
    kohlberg: 5,
    soulAge: "Mature",
    initiationLevel: 3,
    chakras: chakras([60, 56, 60, 62, 52, 54, 34]),
    consciousAspiration: "Keep my little brother out of the life — build something legit",
    soulPurpose: "Break the cycle on his own block, and show the younger ones a way through",
    affinities: { work: 1.5, socialize: 1.3, gaze: 1.1, rest: 1.0 },
    row: "south",
    xMin: 1320,
    xMax: 1560,
    baseSpeed: 20,
  }),

  // Rosangela "Roxy" Valente — Brazilian-American sidewalk survivor and Hidden
  // Protector. Flagged as a future side-quest anchor ("Hollywood Doesn't Sleep").
  // Her circumstance is survival-tier but her SOUL runs high: fearless Throat (she
  // calls out every fake guru on the block), strong Solar Plexus (will), and a Heart
  // kept open for the girls too new to see danger smiling at them. Charm is tactical —
  // armor, not need. She placed near Bailey on purpose: she's watching over her.
  soul({
    id: "roxy_valente",
    name: 'Rosangela "Roxy" Valente',
    occupation: "Walking Tour Guide · Hollywood Blvd",
    archetype: "Streetwise Brazilian Survivor",
    age: 46,
    narrative:
      "Book her tour for the movie trivia; stay for the truth. Tourists see attitude, curves, and sunglasses. The girls who are too new to know better see the one person on this block who'll step between them and a smiling predator. Rio to Newark to here — she survived worse than anything Hollywood can bring. Eu sobrevivi coisa pior.",
    needs: { survival: 46, safety: 48, belonging: 58, esteem: 56, actualization: 58 },
    traits: traits({ antagonism: 50, disinhibition: 42, negativeAffectivity: 38, detachment: 30, psychoticism: 15 }),
    aceScore: 7,
    resilience: 88,
    kohlberg: 5,
    soulAge: "Old",
    initiationLevel: 4,
    chakras: chakras([48, 42, 66, 62, 70, 58, 38]),
    consciousAspiration: "Run my route, stay three steps ahead, make it through another night",
    soulPurpose: "Be the protector she never had — stand between the new girls and the danger that's smiling at them",
    affinities: { work: 1.5, perform: 1.3, socialize: 1.3, gaze: 1.1, hustle: 1.0, rest: 1.0 },
    row: "south",
    xMin: 720,
    xMax: 1000,
    baseSpeed: 13,
  }),

  // Lori Castellano — "The Quiet Broker". Not the Ivar Ave crew's register: an
  // industry/nightlife-adjacent supplier who built real agency and status in a
  // marginalizing economy (grounded in the "queenpin"/psychological-empowerment
  // literature, not the corner-dealer cliché). Kohlberg 5 — a genuinely self-
  // constructed ethical code (harm reduction, hard boundaries), independent of
  // and sometimes in conflict with the law. Her low Belonging locks her Maslow
  // level at "starved for connection" no matter how high her Esteem climbs —
  // the model enforces the same irony the backstory is built on.
  soul({
    id: "lori",
    name: "Lori Castellano",
    occupation: "Independent Supplier, Industry & Nightlife Circuit",
    archetype: "The Quiet Broker",
    age: 37,
    narrative:
      "She spent her twenties as the talent coordinator everyone relied on and nobody promoted — invisible the way competent women in service roles always are. A joke question at a wrap party turned into a supply line into the industry's afterparties and unphotographed dinners. She works relationships and discretion now, not corners, and she's made more than any boss who once passed her over. Everyone in her life needs something from her; she's forgotten how to let anyone need nothing at all.",
    needs: { survival: 78, safety: 45, belonging: 28, esteem: 71, actualization: 26 },
    traits: traits({ negativeAffectivity: 55, detachment: 62, antagonism: 38, disinhibition: 18, psychoticism: 14 }),
    aceScore: 4,
    resilience: 74,
    kohlberg: 5,
    soulAge: "Mature",
    initiationLevel: 2,
    chakras: chakras([55, 45, 76, 24, 58, 34, 12]),
    consciousAspiration:
      "Get enough of a cushion to walk away clean — buy the building, go legitimate, be undeniable on paper the way I already am in practice",
    soulPurpose:
      "See the young women passing through this world the way almost no one else here can — and let that gift protect them, not just herself",
    affinities: { hustle: 1.6, socialize: 1.4, work: 1.2, gaze: 1.1, rest: 1.0 },
    row: "south",
    xMin: 900,
    xMax: 1180,
    baseSpeed: 18,
  }),

  // Nia Brooks — "The Real One". First of a 5-person friend crew being added one
  // at a time. Grounded in the real, documented history of women (especially
  // Black and Latina women) as the uncredited founders of sneaker/streetwear
  // culture — women who built their own communities because the mainstream
  // scene wouldn't recognize them. Her Solar Plexus (esteem) runs low despite
  // real mastery; her Heart is healthier than you'd expect, because the crew
  // she built for herself actually works.
  soul({
    id: "nia",
    name: "Nia Brooks",
    occupation: "Sneaker Reseller & Community Organizer",
    archetype: "The Real One (Underestimated Sneakerhead)",
    age: 24,
    narrative:
      "She's been in this culture since she was twelve, trading Jordans in middle-school hallways before half these resale apps even existed. The scene still treats her like a tourist in her own house, so she stopped waiting for an invitation — built her own group chat for the girls the culture forgets to credit, runs pop-up trades off her fanny pack like a mobile shop, and remembers every name that ever doubted her.",
    needs: { survival: 58, safety: 55, belonging: 62, esteem: 34, actualization: 48 },
    traits: traits({ negativeAffectivity: 48, detachment: 22, antagonism: 46, disinhibition: 30, psychoticism: 15 }),
    aceScore: 3,
    resilience: 78,
    kohlberg: 4,
    soulAge: "Young",
    initiationLevel: 2,
    chakras: chakras([54, 46, 38, 58, 50, 46, 16]),
    consciousAspiration:
      "Make them recognize I built this — get my name said in the culture for real, not as somebody's afterthought",
    soulPurpose:
      "Build the door she had to force open herself so the next overlooked girl never has to fight alone for a seat at the table",
    affinities: { hustle: 1.5, perform: 1.3, socialize: 1.4, work: 1.1, gaze: 1.0, rest: 1.0 },
    row: "north",
    xMin: 950,
    xMax: 1150,
    baseSpeed: 20,
  }),
];
